version: "3.9"

services:
  kokoushuone-mongo:
    image: "mongo:latest"
    restart: "always"
    ports:
      - "27017:27017"
    container_name: kokoushuone-mongo
    volumes:
      - ./mongo_data:/data/db

  kokoushuone-backend:
    image: "ojanenma/kokoushuone-app:backend"
    build:
      context: ./reservatorapp_projekti/ReservatorApp
      dockerfile: Dockerfile
    container_name: kokoushuone-backend
    ports:
      - "4000:4000"
    depends_on:
      - kokoushuone-mongo

  kokoushuone-channel:
    image: "ojanenma/kokoushuone-app:channel"
    build:
      context: ./channel
      dockerfile: Dockerfile
    container_name: kokoushuone-channel
    ports:
      - "3003:3003"

volumes:
  mongo_data:
