version: "3.9"

services:
  reservator-mongo:
    image: "mongo:latest"
    restart: "unless-stopped"
    ports:
      - "27017:27017"
    container_name: resevator-mongo
    volumes:
      - ./mongo_data:/data/db

  reservator-backend:
    image: "ojanenma/kokoushuone-app:backend"
    restart: "unless-stopped"
    build:
      context: ./reservatorapp_projekti/ReservatorApp
      dockerfile: Dockerfile
    container_name: reservator-backend
    ports:
      - "4000:4000"
    depends_on:
      - reservator-mongo

  reservator:
    image: "ojanenma/kokoushuone-app:channel"
    restart: "unless-stopped"
    build:
      context: ./channel
      dockerfile: Dockerfile
    container_name: reservator
    ports:
      - "3003:3003"

volumes:
  mongo_data:
