name: CI Docker

on:
  push:
    branches:
      - "staging"
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./reservatorapp_projekti/ReservatorApp
          file: reservatorapp_projekti/ReservatorApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kokoushuone-app:backend

      - name: Build and push channel
        uses: docker/build-push-action@v3
        with:
          context: ./channel
          file: channel/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kokoushuone-app:channel

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./mock-frontend
          file: mock-frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kokoushuone-app:frontend
  