name: CI Docker

on:
  push:
    branches:
      - "staging"
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./reservatorapp_projekti/ReservatorApp
          file: reservatorapp_projekti/ReservatorApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kokoushuone-app:backend

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Build and copy frontend
        working-directory: ./mock-frontend
        run: |
          cp .env.frontend .env
          npm ci
          npm run build

      - name: Build and push channel
        uses: docker/build-push-action@v3
        with:
          context: ./channel
          file: channel/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kokoushuone-app:channel
