name: Node.js CI

on:
  push:
    branches: ["main", "github_actions"]
  pull_request:
    branches: ["main", "github_actions"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: mock-frontend/package-lock.json

      - name: Build and run tests in the sample project
        run: |
          cd mock-frontend
          npm install
          CI=false npm run build --if-present
          npm test
