name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: mock-frontend/package-lock.json

      - name: Build and run tests in the sample project
        run: |
          cd mock-frontend
          npm install
          CI=false npm run build --if-present

  lint_channel:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: eslint .

  lint_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: eslint .
