name: CI Pipeline

run-name: ${{ github.event_name }} by @${{ github.actor }}

on: [push, pull_request]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock-frontend

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: CI=true npm test

      - name: Build
        run: npm run build

  lint_channel:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: npm run lint

  lint_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mock-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: npm run lint

  lint_reservatorapp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: reservatorapp_projekti/ReservatorApp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm i
      - name: Run ESLint
        run: npm run lint
